### ISSUE TITLE
This is cool, how did you know to use this?

### ISSUE THREAD

**Issue by Siliconrob** [salt-die/Advent-of-Code#2]
https://github.com/salt-die/Advent-of-Code/blob/acad2aed95106f5ac3bcf786bbfdd0612d5a1a3a/2021/day_11.py#L17

**Comment by salt-die** [comment]
Convolutions can be used to count the number of non-zero neighbors a cell has. Let's say we have a random binary array, `a`:
```py
[[1 1 1 1 0]
 [1 0 1 0 0]
 [1 0 1 1 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]
 ```
 If we convolve it with the kernel [[1, 1, 1], [1, 0, 1], [1, 1, ]] (`convolve(a, kernel, mode="constant")`) we get:
```py
[[2 4 3 2 1]
 [3 7 5 5 2]
 [2 5 3 2 1]
 [3 3 3 2 1]
 [1 2 1 0 0]]
 ```
Note that these numbers are exactly the number of non-zero neighbors that the cells in the original array had. You can change the type of neighborhoods you care about by modifying the kernel. If you only want to count neighbors in the four cardinal directions use `kernel = [[0, 1, 0], [1, 0, 1], [0, 1, 0]]`:
```py
[[2 2 3 1 1]
 [2 3 2 3 0]
 [1 3 2 1 1]
 [3 0 2 1 0]
 [0 2 0 0 0]]
 ```
As the convolution in our problem was over the flashing octopuses and it did not matter if they counted themselves as neighbors, I simplified the KERNEL to just be all ones.

Here's an image from [Convolutional Neural Networks (CNNs) in TensorFlow](https://nasirml.wordpress.com/2019/01/08/convnet-in-tensorflow/) to help illustrate:
![external-content duckduckgo com](https://user-images.githubusercontent.com/53280662/145703062-2cf91cfb-c9c3-47bd-92a6-4868e9ad8d12.png)

The kernel is being centered over each cell in the array and we take the sum of the element-wise multiplication.
 
 Here's a better introduction to convolutions by 3Blue1Brown youtuber, Grant Sanderson: [Convolutions in image processing](https://www.youtube.com/watch?v=8rrHTtUzyZA)

**Comment by Siliconrob** [comment]
Thanks.  This was a great idea 💯 to use this
