### ISSUE TITLE
Day 10 - Overflow encountered in scalar add

### ISSUE THREAD

**Issue by CodeByAidan** [salt-die/Advent-of-Code#6]
https://github.com/salt-die/Advent-of-Code/blob/main/2023/day_11.py#L23C5-L27C6

On your day 11 solution, the following lines 23-27:

```py
return sum(
	abs(a - b)
	for axis in (expand(YS, n), expand(XS, n))
	for a, b in combinations(axis, 2)
)
```

will raise a `RuntimeWarning`, mainly when using a significant expansion factor (e.g., 999,999). The warning suggests that an overflow was encountered during scalar addition. To address this issue, consider using a more significant data type for the summation to prevent overflow. You can use `np.int64` or `np.int32` instead of the default data type. Here's an updated version of the `expand_universe` function:

```py
def expand_universe(n):
    return np.sum(
        abs(a - b)
        for axis in (expand(YS, n), expand(XS, n))
        for a, b in combinations(axis, 2),
        dtype=np.int64
    )
```

I love reading your creative solutions, and especially your visualizations! They are so cool! 😄

**Comment by salt-die** [comment]
Oh, i had dtype int64 arrays before, but I "cleaned" up the solution a bit and removed the type. Whoops. Will fix.
